// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WeightLifting.Persistance;

#nullable disable

namespace WeightLiftingPersistance.Migrations
{
    [DbContext(typeof(WeightliftingContext))]
    [Migration("20231124232943_DB_Changes")]
    partial class DB_Changes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeightLiftingPersistance.Model.StartupAttempts", b =>
                {
                    b.Property<int>("AttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttemptID"));

                    b.Property<int>("AthleteID")
                        .HasColumnType("int");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("AttemptID");

                    b.HasIndex("AthleteID");

                    b.ToTable("StartupAttempts");
                });

            modelBuilder.Entity("WeightliftingPersistance.Model.Athletes", b =>
                {
                    b.Property<int>("AthleteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AthleteID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AthleteID");

                    b.ToTable("Athlete", (string)null);
                });

            modelBuilder.Entity("WeightliftingPersistance.Model.PushAttempts", b =>
                {
                    b.Property<int>("AttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttemptID"));

                    b.Property<int>("AthleteID")
                        .HasColumnType("int");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("AttemptID");

                    b.HasIndex("AthleteID");

                    b.ToTable("Attempt", (string)null);
                });

            modelBuilder.Entity("WeightLiftingPersistance.Model.StartupAttempts", b =>
                {
                    b.HasOne("WeightliftingPersistance.Model.Athletes", "Athlete")
                        .WithMany("StartupAttempts")
                        .HasForeignKey("AthleteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("WeightliftingPersistance.Model.PushAttempts", b =>
                {
                    b.HasOne("WeightliftingPersistance.Model.Athletes", "Athlete")
                        .WithMany("PushAttempts")
                        .HasForeignKey("AthleteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("WeightliftingPersistance.Model.Athletes", b =>
                {
                    b.Navigation("PushAttempts");

                    b.Navigation("StartupAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
